#!/bin/bash

sudo  cp   /boot/config.txt  ./boot/config_hdmi.txt 

if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
fi
if [ ! -d /etc/X11/xorg.conf.d ]; then
sudo mkdir -p /etc/X11/xorg.conf.d
fi

root_dev=`grep -oPr "root=[^\s]*" /boot/cmdline.txt | awk -F= '{printf $NF}'`
if test "$root_dev" = "/dev/mmcblk0p7";then
sudo cp -rf ./boot/config-noobs-nomal.txt ./boot/config.txt.bak
else
sudo cp -rf ./boot/config-nomal.txt ./boot/config.txt.bak
sudo echo "hdmi_force_hotplug=1" >> ./boot/config.txt.bak
fi
sudo echo "dtparam=i2c_arm=on" >> ./boot/config.txt.bak
sudo echo "dtparam=spi=on" >> ./boot/config.txt.bak
sudo echo "enable_uart=1" >> ./boot/config.txt.bak
sudo echo "dtoverlay=kedei" >> ./boot/config.txt.bak
sudo cp -rf ./boot/config.txt.bak /boot/config.txt




sudo cp ./boot/inittab /etc/


if test "$1" = "0" -o "$#" = "0";then
sudo cp -rf ./usr/rpi_35_calibration_0.conf /usr/share/X11/xorg.conf.d/99-calibration.conf
sudo cp ./boot/rpi_35_90.dtbo /boot/overlays/kedei.dtbo
echo "LCD displayer 0"
elif test "$1" = "90";then
sudo cp -rf ./usr/rpi_35_calibration_90.conf /usr/share/X11/xorg.conf.d/99-calibration.conf
sudo cp ./boot/rpi_35_180.dtbo /boot/overlays/kedei.dtbo
echo "LCD displayer 90"
elif test "$1" = "180";then
sudo cp -rf ./usr/rpi_35_calibration_180.conf /usr/share/X11/xorg.conf.d/99-calibration.conf
sudo cp ./boot/rpi_35_270.dtbo /boot/overlays/kedei.dtbo
echo "LCD displayer 180"
elif test "$1" = "270"; then
sudo cp -rf ./usr/rpi_35_calibration_270.conf /usr/share/X11/xorg.conf.d/99-calibration.conf
sudo cp ./boot/rpi_35_0.dtbo /boot/overlays/kedei.dtbo
echo "LCD displayer 270"
fi

sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf

sudo  cp ./boot/cmdline.txt   /boot/cmdline.txt

sudo apt-get install xserver-xorg-input-evdev

sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf

sudo sync
sudo sync
sleep 1

sudo reboot
